- drainer/collector.go
- drainer/collector_test.go
- drainer/pump.go
- drainer/schema_test.go
[Jira Issue](https://internal.pingcap.net/jira/browse/TOOL-1044)
Test coverage: 46.3% -> 58.3%
Tests 
- Unit test
Code changes
Side effects
> drainer: Refactor and add unit tests

- pkg/loader/translate.go
- pkg/loader/translate_test.go
[Related Issue](https://internal.pingcap.net/jira/browse/TOOL-1050)
Improve test coverage: 39.1% -> 45.3%
Tests 
- Unit test
Code changes
Side effects
> pkg/loader: Refactor and add tests for translate functions

- pkg/loader/executor.go
- pkg/loader/executor_test.go
- pkg/loader/model.go
- pkg/loader/util.go
[Jira Issue](https://internal.pingcap.net/jira/browse/TOOL-1050)
Improve test coverage: 45.6% -> 61%
Tests 
- Unit test
Code changes
Side effects
> pkg/loader: Refactor and add tests for executor

- pkg/loader/load.go
- pkg/loader/load_test.go
Fix [Jira Issue](https://internal.pingcap.net/jira/browse/TOOL-1050)
Improve tests coverage: 61.1% -> 75.8%
Tests 
- Unit test
Code changes
Side effects
> pkg/loader: Add tests for load

- arbiter/metrics.go
- arbiter/metrics_test.go
- arbiter/server.go
- arbiter/server_test.go
- drainer/metrics.go
- drainer/server.go
- pkg/util/p8s.go
- pkg/util/p8s_test.go
- pump/metrics.go
- pump/server.go
Eliminate duplicate code for starting a goroutine that push metrics.
Extract the common code to util and remove the original duplicate
implementation.
Tests 
- Unit test
Code changes
Side effects
> *: Create a reusable metricClient in util

- .gitignore
- arbiter/config.go
- arbiter/config_test.go
- binlogctl/nodes_test.go
- cmd/arbiter/main.go
- cmd/drainer/main.go
- cmd/pump/main.go
- cmd/reparo/main.go
- drainer/collector.go
- drainer/config.go
- drainer/server.go
- drainer/sync/flash.go
- pkg/binlogfile/binlogger_test.go
- pkg/flags/flag_test.go
- pkg/loader/bench_test.go
- pkg/loader/load_test.go
- pkg/security/security_test.go
- pkg/util/log_test.go
- pkg/util/signal_test.go
- pump/config.go
- pump/server.go
- pump/storage/log_test.go
- pump/storage/storage.go
- pump/storage/vlog_test.go
- reparo/config.go
- reparo/file_test.go
- tests/binlog/binlog.go
- tests/flash/flash.go
Fix some missing error checks as reported by golangci-lint
Tests 
- Unit test
Code changes
Side effects
> *: Fix some missing error checks as reported by golangci-lint

- drainer/collector.go
- drainer/collector_test.go
- drainer/config_test.go
- drainer/server.go
- drainer/server_test.go
- drainer/util.go
- drainer/util_test.go
[Jira Issue](https://internal.pingcap.net/jira/browse/TOOL-1044)
Improve tests coverage: 60% -> 70%
Tests 
- Unit test
Code changes
Side effects
> drainer: Add unit tests

- drainer/collector.go
- drainer/config.go
- drainer/sync/kafka.go
- pkg/node/registry.go
- pkg/util/log.go
- pump/storage/log.go
- pump/storage/storage.go
- reparo/config.go
There are some misspelled words in comments and help messages.
Fix the misspelled words.
Tests 
- No code
Code changes
Side effects
> *: Fix typos

- binlogctl/meta.go
- binlogctl/meta_test.go
- binlogctl/nodes.go
- binlogctl/nodes_test.go
improve test coverage
add unit test, from 63% to 79%
Tests 
- Unit test
> binlogctl: add unit test

- CHANGELOG.md
CHANGELOG.md: Add 2.1.10
Tests 
- No code
Code changes
Side effects
> CHANGELOG.md: Add 2.1.10

- pkg/util/util.go
- pkg/util/util_test.go
- pump/node.go
- pump/node_test.go
- pump/server.go
- pump/server_test.go
[Jira Issue](https://internal.pingcap.net/jira/browse/TOOL-1056) 
Improve tests coverage: 44.2% -> 54.6%
Tests 
- Unit test
Code changes
Side effects
> pump,pkg/util: Refactor and add more unit tests

- README.md
Add 2 new badges.
The following badges are added:
1. build status
2. go report
Tests 
- No code
Code changes
Side effects
> doc: Add more badges on README

- pump/storage/log.go
- pump/storage/storage.go
- pump/storage/vlog.go
Refine some log in storage/
cherry-pick https://github.com/pingcap/tidb-binlog/pull/607
Tests 
Code changes
Side effects
> pump/*: Refine some log in storage/ (#607)

- tests/run.sh
We can't select more than one integration test case to run.
Support selecting multiple cases to run.
Tests 
Code changes
Side effects
> tests: Support selecting multiple cases to run

- pump/storage/storage.go
- pump/storage/vlog.go
Clean up come code in pump/storage.
1. Use predefined constants in leveldb/opt to improve readability of
leveldb config values.
1. Use path/filepath and strings functions to simplify path manipulation
1. Rename confusing variable
Tests 
- Unit test
Code changes
Side effects
> pump/storage: Random cleanups

- pkg/util/util.go
- pkg/util/util_test.go
- pump/config.go
- pump/config_test.go
- tests/_utils/run_pump
Fix #627
1. Reuse `IsValidateListenHost` for checking `advertiseHost`
1. Make sure empty string is invalid
Tests 
- Unit test
- Manual test
Code changes
Side effects
> *: empty host should not be considered valid, fix #627

- pkg/util/kafka.go
- pkg/util/util_test.go
- reparo/syncer/mysql.go
- reparo/syncer/mysql_test.go
- reparo/syncer/translate_test.go
- reparo/syncer/util_test.go
add some unit tests, mainly in `pkg` and `reparo/syncer module`
add test cases to cover some not tracked code
Tests 
- Unit test
> *: add some unit tests and remove unused code

- pkg/util/util.go
- pkg/util/util_test.go
- pump/node.go
Fix #560
Retry connection and request.
Tests 
- Unit test
Code changes
Side effects
> pump: Fix #560, retry connection and request when notifying drainers

- cmd/drainer/drainer.toml
- drainer/config.go
- drainer/config_test.go
- drainer/server.go
- pkg/util/util.go
- pump/config.go
- pump/config_test.go
- tests/_utils/run_pump
Cherry pick and adapt the following 3 PRs:
1. https://github.com/pingcap/tidb-binlog/pull/629
1. https://github.com/pingcap/tidb-binlog/pull/637
1. https://github.com/pingcap/tidb-binlog/pull/634
1. Support configuring advertise-addr for drainer
1. Check for empty host in config
Tests 
- Unit test
- Manual test
Code changes
Side effects
> Cherry pick advertise-addr related changes from master

- reparo/config.go
- reparo/reparo.go
- reparo/syncer/mysql.go
- reparo/syncer/mysql_test.go
- reparo/syncer/syncer.go
- reparo/syncer/syncer_test.go
fix issue https://internal.pingcap.net/jira/browse/TOOL-1333
1 update log
2 add safe mode config
Tests 
- Unit test
> reparo: add safe mode config

- pump/storage/sorter.go
- pump/storage/sorter_test.go
- pump/storage/storage_test.go
- pump/storage/vlog_test.go
Make the unit tests of pump/storage run faster.
Use smaller test data and shorter wait times.
Tests 
- Unit test
Code changes
Side effects
> pump/storage: More lightweight unit tests

- pump/storage/vlog.go
The original implementation of `valueLog.scan` assumes it
would only be called when pump is starting up, during which time no
writing is happening.
So it's OK to hold a lock that blocks `valueLog.write`.
There are 2 steps in `valueLog.write` that use the `filesLock`:
1. Looking up the `logFile` for `maxFid` (Read)
1. Creating a new `logFile` (Write)
Only the second case requires a write lock.
If we make `scan` acquire the read lock instead, case 1 would not be
blocked at all.
But the second case would still be blocked if we need to hold the read
lock in scan until all logFiles are processed.
1. Use `RLock` instead to get all the selected logFiles.
1. Scan without holding the lock.
This is acceptable because:
1. If `scan` is used when pump is starting up, no concurrent writes
exist, so …
> pump/storage: Only hold the lock when collecting logFiles to scan

- pump/storage/storage_test.go
- pump/storage/vlog.go
- pump/storage/vlog_test.go
Some recently added functions are not tested.
Add a test.
Tests 
- Unit test
Code changes
Side effects
> pump: Add more tests for pump/storage

- pkg/loader/load.go
- pkg/loader/load_test.go
pkg/loader: set finish ts in markSuccesses
`batchManager` is a helper struct to handle batch execution of transactions.
What we need here is to set the matching slave ts of a transaction successfully synced to the downstream/slave, so I think `markSuccesses` is a better place.
Refactor by moving the setting finish ts implementation to `markSuccesses`.
Tests 
- Unit test
Code changes
Side effects
> Set finish ts in markSuccesses which is a natural match to handleSuccesses

- tests/dailytest/case.go
There's no tests for the case of VIEW creation.
Add the missing test case.
Tests 
Code changes
Side effects
> tests: Add integration test case for view creation

- pump/storage/errors.go
- pump/storage/storage.go
fix https://github.com/pingcap/tidb-binlog/issues/679
output more information about available and the stop-at-write configaration.
Tests 
- Unit test
Code changes
Side effects
> pump/: Refine log when no available space

- pkg/sql/sql.go
add the key not exist as ignore ddl error
cherry-pick https://github.com/pingcap/tidb-binlog/pull/683
Tests 
- Unit test
Code changes
Side effects
> pkg/sql: add missing error code of IgnoreDDLError 

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/general-question.md
[TOOL-1463](https://internal.pingcap.net/jira/browse/TOOL-1463)
Add issue templates for bugs, features, questions to help contributors to propose an issue.
The effect of this PR is shown at [here](https://github.com/lichunzhu/tidb-binlog/issues/new/choose).
Tests
Code changes
Side effects
> add issue templates for bugs, features, questions

- go.mod
- go.sum
update parser in go.mode & go.sum to synchronize binlog with tidb.
Tests 
- Unit test
Code changes
Side effects
> update parser in go.mode & go.sum to tidb release 2.1

- drainer/syncer.go
`itemsWg` is not used anywhere.
Remove the unused wait group.
Tests 
- Unit test
Code changes
Side effects
> drainer: Remove unused waitGroup

- drainer/translator/flash.go
- drainer/translator/kafka.go
- drainer/translator/mysql.go
- drainer/translator/pb.go
columnValues will be nil and panic
Tests 
- Unit test
- No code
Code changes
Side effects
> *: Fix if only one column and pk is not handle

- pump/node.go
- pump/server.go
cherry-pick #709 to release-2.1
> fix pump init order, register the node after listen ports (#709)

- pkg/etcd/etcd.go
- pkg/etcd/etcd_test.go
- pkg/zk/zk_test.go
close etcd client and zk client before test case teardown
add close call
Tests 
- Unit test
Code changes
Side effects
> pkg: add resource close in test case

- pump/node_test.go
[TOOL-1056](https://internal.pingcap.net/jira/browse/TOOL-1056)
Mock a fake grpc drainer to be notified. Mocked drainer will occupy port 8249 for a while.
Tests 
- Unit test
Code changes
Side effects
> add drainer notify test for pump node

- Makefile
- drainer/pump.go
same with https://github.com/pingcap/tidb-binlog/pull/432
> drainer/* Fix not skip rollback state ddl job

- pump/storage/storage.go
- pump/storage/storage_test.go
> test: add test for metadata gc (#728)

- Makefile
- binlogctl/config.go
- binlogctl/config_test.go
- binlogctl/meta.go
- binlogctl/meta_test.go
- binlogctl/nodes.go
- binlogctl/nodes_test.go
- cmd/binlogctl/README.md
- cmd/binlogctl/main.go
- pkg/node/node.go
- pkg/util/ts.go
copy code from master branch
cp ...
Tests 
- Unit test
> *: add binlogctl

- tools/check/check-tidy.sh
The original script fails quietly, we can't easily check what's causing
the failed build.
Output a help message.
Tests 
- Manual test
Code changes
Side effects
> *: Output user friendly msg when go mod tidy is needed

- drainer/merge.go
> merge.go: Distinct disorder and duplicate cast in log

- pump/server.go
Add warn log for slow response
Add warn log for slow response
Tests 
Code changes
Side effects
> pump/server.go: Add warn log for slow response

- pump/server.go
Add warn log for slow response
cherry pick #765
> pump/server.go: Add warn log for slow response (#765)

- cmd/drainer/drainer.toml
- drainer/config.go
- drainer/config_test.go
- tests/binlog/drainer.toml
- tests/filter/drainer.toml
- tests/gencol/drainer.toml
- tests/kafka/drainer.toml
- tests/reparo/drainer.toml
- tests/restart/drainer.toml
- tests/status/drainer.toml
drainer/*: use enable-** in 4.0
drainer/*: use enable-** in 4.0
Tests 
Side effects
> drainer/*: use enable-** in 4.0

- pkg/loader/load_test.go
Some unit tests are not stable and may fail by chance.
1. Use channel to communicate completion of steps
1. Wait longer 
Tests 
- Unit test
Code changes
Side effects
> pkg/loader: Fix unstable unit tests

- go.mod
- go.sum
Tests 
- Unit test
- No code
Code changes
Side effects
> update tool dependency

- go.mod
- go.sum
Tests 
- Unit test
- No code
Code changes
Side effects
> update tidb tools dependency

- binlogctl/config.go
- binlogctl/nodes.go
- binlogctl/nodes_test.go
- cmd/binlogctl/main.go
- tests/_utils/check_status
> binlogctl: Only show offline nodes when explicitly told so (#774)

- drainer/collector.go
- drainer/server.go
- pkg/loader/bench_test.go
- pkg/loader/executor.go
- pkg/loader/load.go
- pump/server.go
- pump/status.go
- pump/storage/chaser_test.go
- pump/storage/storage.go
Many returned errors are not checked.
Check and handle those errors.
Tests 
- Unit test
Code changes
Side effects
> *: Check errors

- Makefile
- drainer/server.go
- drainer/server_test.go
- drainer/status.go
- pump/node_test.go
- pump/server.go
- pump/server_test.go
- pump/storage/log.go
The errcheck analysis is disabled because there are still many places where the returned error is unchecked.
Add missing error checks and enable errcheck.
Tests 
- Unit test
> *: Add missing error checks and enable errcheck in static-check

- pump/storage/storage.go
There's no log for this case.
Add the log.
Tests 
- Unit test
> pump: Add a log for when MVCC is not found for a txn not yet GCed

- go.mod
- go.sum
Update parser as latest verison tidb use
Update parser as latest verison tidb use
Tests
> Update parser as latest verison tidb use

- go.mod
- go.sum
Update parser as the latest version tidb use
Update parser as the latest version tidb use
Tests
> Update parser as the latest version tidb use

- go.mod
- go.sum
Use format tidb-tools, forget to change back in #858 
use the version added unique info
Tests
> Use format tidb-tools

- drainer/checkpoint/file_test.go
- drainer/relay_test.go
- drainer/sync/mysql.go
- drainer/sync/syncer.go
- drainer/syncer.go
- drainer/translator/mysql.go
- drainer/translator/mysql_test.go
- pkg/loader/executor.go
- pkg/loader/executor_test.go
- pkg/loader/load.go
- pkg/loader/load_test.go
- pkg/loader/model.go
- pkg/loader/model_test.go
- reparo/syncer/mysql_test.go
- reparo/syncer/print_test.go
- reparo/syncer/translate_test.go
> Fix current DML&DDL corner case for bidirectional replication  (#890)

- go.mod
- go.sum
- tests/dailytest/case.go
- tests/run.sh
Update parser add test for auto_random
Update parser add test for auto_random
Tests 
Code changes
Side effects
> Update parser add test for auto_random

- drainer/sync/kafka.go
- drainer/sync/mysql.go
- drainer/sync/pb.go
- drainer/sync/syncer.go
- drainer/syncer.go
add SetSafeMode to Drainer's Syncer interface.
Tests 
- Unit test
> modify Drainer 's Syncer interface

- drainer/sync/kafka.go
- drainer/sync/mysql.go
- drainer/sync/pb.go
- drainer/sync/syncer.go
- drainer/syncer.go
cherry-pick https://github.com/pingcap/tidb-binlog/pull/956
add SetSafeMode to Drainer's Syncer interface.
Tests 
- Unit test
> modify syncer interface (#956)

- tests/partition/drainer.toml
- tests/partition/run.sh
- tests/run.sh
Add test cases for table partition.
Only add a new test case. No logical code is modified.
Tests 
Code changes
N/A
Side effects
N/A
N/A
> test: add test cases for range/hash partition

- pump/node.go
pick #971 Fix notify drainer not enable tls
Fix notify drainer not enable tls
Tests 
check the new started pump in /tests/restart/run.sh do can be started.
- Fix pump notify drainer not enable TLS.
> Fix notify drainer not enable tls

- arbiter/server.go
- drainer/checkpoint/checkpoint.go
- drainer/checkpoint/file.go
- drainer/checkpoint/mysql.go
- drainer/checkpoint/mysql_test.go
- drainer/relay.go
- drainer/relay/reader.go
- drainer/relay/reader_test.go
- drainer/relay/relayer.go
- drainer/sync/kafka.go
- drainer/syncer.go
- drainer/translator/kafka.go
- drainer/translator/kafka_test.go
- pkg/filter/filter.go
- pkg/loader/README.md
- pkg/loader/load.go
- pkg/loader/translate.go
- pkg/loader/translate_test.go
- pkg/sql/sql.go
- tests/kafka/kafka.go
update black/white list to block/allow list && update master/slave to primary/secondary
update word
> update black/white list and some description about master/slave

- drainer/config.go
- drainer/relay.go
- drainer/sync/mysql.go
- drainer/sync/syncer_test.go
- drainer/sync/util.go
- pkg/loader/util.go
close https://github.com/pingcap/tidb-binlog/issues/981
Set `tidb_txn_mode` to `optimisstic` as default to improve effiency.
Tests 
- Unit test
Code changes
- support tidb_txn_mode for drainer dsync and use `optimistic` as default.
> support tidb txn mode option

- drainer/relay.go
- drainer/sync/mysql.go
- drainer/sync/syncer_test.go
- drainer/sync/util.go
- pkg/loader/util.go
cherry-pick #1003
---
close https://github.com/pingcap/tidb-binlog/issues/981
Set `tidb_txn_mode` to `optimisstic` as default to improve effiency.
Tests 
- Unit test
Code changes
- support tidb_txn_mode for drainer dsync and use `optimistic` as default.
> support tidb txn mode option (#1003)

- go.mod
- go.sum
update TiDB for https://github.com/pingcap/tidb/pull/21706
```
go get -u github.com/pingcap/tidb@9ab0bbf9a012aaf8ae2d3e1eee2a321e03a0d5c1
go mod tidy
```
Tests 
- No code
Code changes
Side effects
- No Release note.
> *: update go mod for TiDB

- tests/run.sh
Fix image not found in CI
comment changed to generate a PR for 5.0-rc
Tests 
- No code
> CI: Fix image not found in CI

- arbiter/config_test.go
- binlogctl/meta.go
- binlogctl/meta_test.go
- cmd/arbiter/main.go
- drainer/checkpoint/file.go
- drainer/config_test.go
- drainer/pump_test.go
- drainer/server_test.go
- go.mod
- go.sum
- pkg/binlogfile/binlogger_test.go
- pkg/binlogfile/file_test.go
- pkg/file/lock_test.go
- pkg/security/security.go
- pkg/security/security_test.go
- pkg/util/util.go
- pump/config_test.go
- pump/node.go
- pump/node_test.go
- pump/server_test.go
- pump/storage/log_test.go
- pump/storage/vlog.go
- reparo/config_test.go
- tests/run.sh
- tools/check/go.mod
cherry-pick https://github.com/pingcap/tidb-binlog/pull/1051 and https://github.com/pingcap/tidb-binlog/pull/1048
Tests 
- Unit test
- Fix integration test, update go to v1.16 and replace ioutils
> *: chery-pick several PRs to release v5.1

- go.mod
- go.sum
- tests/_utils/check_data
- tests/reparo/run.sh
- tests/reparo/sync_diff_inspector.toml
- tests/restart/sync_diff_inspector.toml
Signed-off-by: Ryan Leung <rleungx@gmail.com>
Update the tidb-tools dependency.
Just as the title says.
Tests 
- Unit test
Release note
> Update tidb-tools dependency

- go.mod
- go.sum
- tests/_utils/check_data
- tests/reparo/run.sh
- tests/reparo/sync_diff_inspector.toml
- tests/restart/sync_diff_inspector.toml
update tidb dependencies to newest release-4.0
update tidb dependencies to newest release-4.0
Tests 
- Unit test
> dependencies: update tidb dependencies

- Makefile
- drainer/syncer.go
- drainer/util.go
- pkg/loader/load.go
- pkg/loader/load_test.go
replicate ddl data in binlog to oracle
Tests 
- Unit test
- No code
Code changes
Side effects
> replicate ddl data in binlog to oracle

- tests/_utils/check_data
- tests/reparo/run.sh
- tests/reparo/sync_diff_inspector.toml
- tests/restart/sync_diff_inspector.toml
cherry-pick #1084
update sync-diff conf to pass integration tests
Tests 
- Unit test
> tests: update sync-diff conf

- .github/pull_request_template.md
> add issue requirement to pull request template

- drainer/checkpoint/checkpoint.go
- drainer/checkpoint/mysql_test.go
- drainer/checkpoint/oracle.go
- drainer/checkpoint/oracle_test.go
- drainer/checkpoint/util.go
- drainer/sync/mysql.go
- drainer/sync/util.go
- drainer/util.go
- drainer/util_test.go
- pkg/loader/load.go
- pkg/sql/sql.go
- pkg/sql/sql_test.go
using oracle db as a checkpoint storage
Tests 
- Unit test
- No code
Code changes
Side effects
> adaptation to oracle checkpoint

- pkg/loader/util.go
- tests/placement_rules/run.sh
Issue Number: close #1140
Set `tidb_placement_mode` to `ignore` in DSN to ignore all tidb placement operations.
Tests 
Upstream and downstream are all TiDB. In update stream:
```
create placement policy pn followers=1;
create table t1(id int) placement policy pn;
```
The result in down stream:
```
mysql> show placement;
Empty set (0.01 sec)
mysql> show create table t1;
+-------+-------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                |
+-------+-------------------------------------------------------------------------------------------------------------+
| t1    | …
```
> drainer: Ignore all tidb placement operations

- drainer/server.go
- pkg/loader/load_test.go
- pump/node.go
- tests/restart/run.sh
Issue Number: close https://github.com/pingcap/tidb-binlog/issues/1154
Make notify drainer request not nil
Tests 
- Unit test
Code changes
- None
Side effects
- None
- None
> pump: try to fix marshal marshaling: proto: Marshal called with nil error

- drainer/syncer.go
Issue Number: close #xxx
fix version not found
Tests 
- Unit test
- No code
Code changes
Side effects
> fix version

- drainer/config.go
- drainer/schema.go
- drainer/schema_test.go
- drainer/server.go
- drainer/util.go
Issue Number: close #xxx
Tests 
- Unit test
- No code
Code changes
Side effects
> drainer: load table infos from kvstorge

- drainer/schema.go
- drainer/syncer.go
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>
Issue Number: close #1179
Init `mysql` schema after creating a new schema.
Tests 
According to #1179, the drainer can get started and work after this PR.
Side effects
> drainer: support concurrent DDL

- reparo/config.go
- reparo/decode.go
- reparo/http_handler.go
- reparo/metrics.go
- reparo/reparo.go
- reparo/syncer/mysql.go
- reparo/syncer/mysql_test.go
- reparo/syncer/syncer.go
- reparo/syncer/syncer_test.go
Issue Number: close #xxx
Support pprof and http metrics serving for reparo.
Tests 
- Manual test
Code changes
- None
Side effects
- None
- None
> reparo: support pprof and metrics

- pkg/loader/load.go
- pkg/loader/load_test.go
Issue Number: ref #1175 https://github.com/pingcap/tiflash/issues/5252
Because we remove the ddl 'set tiflash mode', thus we need to remove the related code about this ddl.
Tests 
- Unit test
- No code
Code changes
Side effects
> Remove related code for ddl 'set tiflash mode'

- Makefile
- drainer/schema.go
Issue Number: close #xxx
Tests 
- Unit test
- No code
Code changes
Side effects
> drainer: fix release 0830 unit test

- drainer/schema.go
- drainer/syncer.go
Issue Number: close https://github.com/pingcap/tidb-binlog/issues/1250
skip all ddl system tables
Tests 
- Unit test
test use new drainer to do upgrade and it works
Code changes
- None
Side effects
- None
```release-note
None
```
> drainer: fix ddl system table

- OWNERS_ALIASES
- cmd/OWNERS
Issue Number: close #1289
Tests 
- Unit test
- No code
Code changes
Side effects
```
None
```
> CI: strict control the changes on `cmd` folder
