README.md
arbiter/metrics.go
arbiter/metrics_test.go
arbiter/server.go
arbiter/server_test.go
binlogctl/config.go
drainer/collector.go
drainer/collector_test.go
drainer/pump.go
drainer/schema_test.go
drainer/server.go
drainer/translator/translator.go
drainer/util.go
drainer/util_test.go
tests/dailytest/case.go

rebase master
git rebase master

release 3.0 rebase master

---

go.mod
go.sum
pkg/loader/executor.go

Since 1.11.1, `errors.Trace` would skip adding stack to `nil`s.
Version of `errors.Trace`: 1.11.0 -> 1.11.1
Tests 
- Unit test
Code changes
Side effects

*: Upgrade to pingcap/errors@v1.11.1

---

drainer/pump.go
drainer/pump_test.go

Although empty compressor name seems to be ignored by grpc anyway, we'd
better not depend on undocumented behaviors.
Make sure empty compressors are ignored.
Tests 
- Unit test
Code changes
Side effects

drainer: Ignore empty string when getting compressor config

---

drainer/config.go

Drainer logs a fatal error when it encounters an attempt to bind to 127.0.0.1 or localhost. The concern seems to be that pump will not be able to contact the drainer in this case? This is not a very reasonable assumption, since someone might run a local cluster for testing or use port forwarding.
This PR changes the fatal error to a warning.

Turn fatal error listening on 127.0.0.1/localhost into a warning (was #561)

---

go.mod
go.sum

update to the version which tidb 2.1 use.
before this pr, fail to parser this SQL:
create table a(id int, a varchar(30) NOT NULL COMMENT 'aa' COLLATE
'utf8_bin');
`GO111MODULE=on go get github.com/pingcap/parser@361d2d4f774d`
Tests 
run the sql as desc before
Code changes
Side effects

go.mod: Update parser dep

---

pkg/loader/load.go

the default value is only 2, and may change for future release of go
when the worker count if hight, this will cause two many connection
create and close.
set max idle conns as worker count
the default value is only 2, and may change for future release of go
when the worker count if hight, this will cause two many connection
create and close every time we use `sql.DB`.
set max idle conns as worker count
Tests 
worker-count = 64
before this pr, it may create and close connection frequencly, and not port available more.
need wait `TIME_WAIT` before reuse port.
```
[2019/05/21 10:17:49.618 +08:00] [ERROR] [util.go:147] [singleExec] [error="dial tcp 172.16.4.71:3306: connect: cannot assign requested address"] [errorVerbose="dial tcp 172.16.4.71:3306: connect: cannot assign requested …
```

load.go: set max idle conns as worker count

---

pump/server.go

When we call `Close` on the server, it first calls `cancel`
to stop all related background jobs. If we reuse `s.ctx` in
`getSafeGCTSOForDrainers` after `Close`, nothing useful can be done.
Make `ctx` a parameter, so that when calling `getSafeGCTSOForDrainers`
after `Close` we can pass in a different context.
Tests 
Code changes
Side effects

pump: getSafeGCTSOForDrainers should be usable after Close

---

drainer/metrics.go
drainer/syncer.go

Fix [Jira Issue](https://internal.pingcap.net/jira/browse/TOOL-1170)
A new metric `checkpoint_delay = now() - most-recent-ts` is included.
Tests 
Manual test (confirmed that the new metric appeared in the /metrics endpoint):  
```
binlog_drainer_checkpoint_delay_seconds 15.128
```
Code changes
Side effects

drainer: Add a metric to track the delay of the downstream

---

drainer/syncer.go
drainer/translator/flash_util.go

Fix golint complaints
1. Use `fmt.Errorf`
1. Remove unnecessary `nil` initialization
Tests 
- Unit test
Code changes
Side effects

*: Fix golint complaints

---

pkg/loader/load.go
pkg/loader/load_test.go
reparo/syncer/translate.go
reparo/syncer/translate_test.go
tests/reparo/binlog.go
tests/reparo/config.toml
tests/reparo/reparo.toml
tests/reparo/run.sh
tests/reparo/sync_diff_inspector.toml

reparo's integration test is too simple, should refine it
1. use daily test in reparo's integration test
2. find a bug, after exec DDL, loader will refresh table info, but the DDL.Database and DDL.Table is empty, and the DML will execute failed because use old table info.
Tests 

reparo: refine integration test

---

drainer/syncer.go

[Related Issue](https://internal.pingcap.net/jira/browse/TOOL-1235?filter=-2)
The failure of `s.dsyncer.Close` may cause the following
`wg.Wait()` to block forever, we don't even have a chance to look at the
returned error.
Log the close error before starting to block waiting, and log long
waits.
Tests 
- Unit test
Code changes
Side effects

drainer: Log close error and long waits

---

pkg/sql/sql_test.go

In `ExecuteTxn` test, we execute two SQLs with some delay (101ms, 201ms) via sql mock.
the original check range for histogram sample_sum is [0.302, 0.357], these two metrics bound reflect the delay from `txn.Exec(...)` to `histogram.WithLabelValues("exec").Observe(...)`, from  302ms to 357ms.
We can have a more accurate upper bound based on execution time observing from test case. (sometime the execution time may even exceed 357ms)
change the check range to (0.302, observing upper bound)
Tests 
- Unit test

tests: fix the value range when checking exec txn histogram

---

cmd/pump/pump.toml
pump/server.go
pump/storage/storage.go
pump/storage/vlog.go

let user to set 
* the kv channel capacity to buffer  more binlog meta
* output binlog meta information if pump take a long time to write binlog
add configuration items for pump storage under [storage] configuration
``` 
#
```
Tests 

pump: Add config to set cap buf of kv_chan

---

tests/dailytest/case.go

easy to meet "TiKV Server timeout" at CI while commit this txn
easy to meet "TiKV Server timeout" at CI while commit this txn
reduce txn size of test case binlog_big
Tests 
Code changes
Side effects

tests: Reduce binlog_big test txn data

---

pkg/binlogfile/binlogger.go
pkg/binlogfile/binlogger_test.go

One of the unit tests of pkg/binlogfile sometimes
[fails](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/binlog_ghpr_unit_test/detail/binlog_ghpr_unit_test/476/pipeline/):
```
[2019/06/14 09:57:29.008 +08:00] [WARN] [binlogger.go:339] ["binlog file
is already reach the gc time, but data is not send to kafka, position is
%v"]
[name=/tmp/check-6129484611666145821/2/binlog-0000000000000000-20190614095728]
[position={}]
----------------------------------------------------------------------
FAIL: binlogger_test.go:205: testBinloggerSuite.TestGC
binlogger_test.go:225:
c.Assert(names[0], Equals, BinlogName(0))
... obtained string = "binlog-0000000000000000-20190614095728"
... expected string = "binlog-0000000000000000-20190614095729"
```
Don't use `BinlogName` when checking …

pkg/binlogfile: Fix test

---

pump/config.go
pump/config_test.go

Allow 127.0.0.1 for testing.
Check for empty host and 0.0.0.0 explicitly.
Tests 
- Unit test
Code changes
Side effects

pump: Allow 127.0.0.1 for advertise-addr

---

cmd/drainer/main.go

Fix issue #242.
Make sure users can see which version of drainer they are using easily,
even when it fails to start because of misconfiguration.
Log version info when drainer is started.
Tests 
- Manual test
Added an invalid `zookeeper-addrs` to drainer.toml and make sure that
the version info was still outputed.
Code changes
Side effects

drainer: Log version info before other logs, fix #242

---

pump/storage/vlog.go
pump/storage/vlog_test.go

cherry-pick https://github.com/pingcap/tidb-binlog/pull/640
cherry-pick https://github.com/pingcap/tidb-binlog/pull/640
Tests 
- Unit test
Code changes
Side effects

vlog.go: Fix wrongly maintain the offset of file in memory (#640)

---

cmd/binlogctl/main.go

binlogctl not return error when cmd is not supported
Tests 
- Manual test

binlogctl: return error when cmd not supported

---

cmd/drainer/main.go

Reverts pingcap/tidb-binlog#638
it alway log the `[2019/06/21 21:12:25.917 +08:00] [INFO] [version.go:50.....`
```
➜  bin git:(master) ✗ ./drainer -V
[2019/06/21 21:12:25.917 +08:00] [INFO] [version.go:50] ["Welcome to Drainer"] ["Release Version"=v3.0.0-rc.2-18-ge77e090d] ["Git Commit Hash"=e77e090d6c7843e4226f91825bcfd5564b4f4837] ["Build TS"="2019-06-21 01:06:43"] ["Go Version"=go1.12.5] ["Go OS/Arch"=darwin/amd64]
Release Version: v3.0.0-rc.2-18-ge77e090d
Git Commit Hash: e77e090d6c7843e4226f91825bcfd5564b4f4837
Build TS: 2019-06-21 01:06:43
Go Version: go1.12.5
Go OS/Arch: darwin/amd64
➜  bin git:(master) ✗ ./drainer -h
[2019/06/21 21:12:28.587 +08:00] [INFO] [version.go:50] ["Welcome to Drainer"] ["Release Version"=v3.0.0-rc.2-18-ge77e090d] ["Git Commit …
```

Revert "drainer: Log version info before other logs, fix #242"

---

pump/storage/storage_test.go
pump/storage/vlog_test.go

With big inputs like "writing a 500MB binlog", the unit tests of
pump/storage can be very slow.
1. Remove big inputs.
1. Batch valueLog writes
Tests 
- Unit test
Code changes
Side effects

pump/storage: Avoid big inputs that slow down the unit test

---

cmd/binlogctl/main.go
go.mod
go.sum
pump/server.go
pump/storage/storage.go
pump/storage/vlog.go

Refine gc of pump
1, Add a API to trigger gc
2, Check L0 files by *GetProperty* instead of Stats
Stats can't get the right L0 files num, see:
https://github.com/syndtr/goleveldb/pull/283/files
3, call vlog.gcTS step by step, help free space quickly
4,   update goleveldb dependency
only one new commit
https://github.com/syndtr/goleveldb/commit/02440ea7a28525b3079783ad9c27083994a42366
Fix the stat about levels of the Stats API
Tests 
- Unit test
call `debug/gc/trigger`
Code changes
Side effects

pump/: Fix get L0 files num and trigger vlog.gcTS step by step

---

cmd/binlogctl/main.go
cmd/pump/pump.toml
go.mod
pump/server.go
pump/server_test.go
pump/storage/errors.go
pump/storage/storage.go
pump/storage/util.go
pump/storage/util_test.go
pump/storage/vlog.go

pump: Add support to stop write at a limit avaliable space
Add a configuration to stop writes at a limit available space size.
Tests 
- Unit test
use `dd` make space less than configured size -> write failed -> delete file make enough space -> write succes 
Code changes
Side effects

pump: Add support to stop write at a limit avaliable space

---

pump/storage/log.go
pump/storage/log_test.go
pump/storage/vlog.go

When we need to make sure the `writableOffset` is for the file
corresponding to `maxFid`, we may write code like this:
```go
if fid == maxFid {
// get writableOffset
}
```
To make this threadsafe, we have to introduce a lock.
Separate the concern of the struct `valueLog` and `logFile`.
`valueLog` is a higher level interface to the binlog data files, it
manages a directory of `logFile`s.
`logFile` is responsible for saving data to individual files.
By allowing `LogFile` to manage its own `writeOffset`, we can be sure
that the offset is for the "current" file without using a lock.
Tests 
- Unit test
Code changes
Side effects

pump/storage: Refactor, encapsulate writing and offset updating in logFile

---

pump/storage/storage.go

LevelDB iterator may return error, better to check it after the iterator is exhausted 
check error and add error log if needed
Tests 
- Unit test

pump: record levelDB iterator error during gc

---

drainer/translator/mysql.go
tests/update_bit1/drainer.toml
tests/update_bit1/run.sh

Issue TOOL-1346, which is caused by pingcap/tidb#10988.
Encode BIT types as integers instead of byte strings. Since the longest value is BIT(64), it is safe to always convert as `uint64`.
Tests 
* Verified the repro steps in TOOL-1346 are no longer reproducible.
Code changes
Side effects
* Needs to cherry-pick to the release-2.1 branch.

drainer: fix failure to update BIT columns with downstream TiDB

---

drainer/translator/mysql.go
tests/update_bit1/drainer.toml
tests/update_bit1/run.sh

Cherry-pick #655 to release-2.1.
Tests 
- Unit test
Code changes
Side effects

[release-2.1] drainer: fix failure to update BIT columns with downstream TiDB (#655)

---

go.mod
go.sum
pump/server.go
pump/storage/storage.go
pump/storage/vlog.go

cherry-pick https://github.com/pingcap/tidb-binlog/pull/648
1, Add a API to trigger gc
2, Check L0 files by GetProperty instead of Stats
Stats can't get the right L0 files num, see:
https://github.com/syndtr/goleveldb/pull/283/files
3, call vlog.gcTS step by step, help free space quickly
4, update goleveldb dependency
only one new commit
syndtr/goleveldb@02440ea
Fix the stat about levels of the Stats API
Tests 
Code changes
Side effects

[release-2.1] pump/: Fix get L0 files num and trigger vlog.gcTS step by step (#648)

---

cmd/pump/pump.toml
go.mod
pump/server.go
pump/storage/errors.go
pump/storage/storage.go
pump/storage/util.go
pump/storage/util_test.go
pump/storage/vlog.go

Default set it 10 gib
cherry-pick https://github.com/pingcap/tidb-binlog/pull/647
Add a configuration to stop writes at a limit available space size.
Tests 
Code changes

[release-2.1] pump: Add support to stop write at a limit avaliable space (#647)

---

drainer/translator/pb.go
pkg/dml/dml.go
pkg/loader/executor.go
pkg/loader/model.go

Space of some slices and strings with known size are not preallocated.
(As reported by the static analysis tool:
[prealloc](https://github.com/alexkohler/prealloc))
Preallocate space for slices and strings of known size.
Tests 
- Unit test
Code changes
Side effects

*: Preallocate space for slices and strings

---

cmd/reparo/reparo.toml

WX added the safe-mode config in reparo with https://github.com/pingcap/tidb-binlog/pull/652, this PR updates the reparo example config file. 
Add the safe-mode config in /cmd/reparo/reparo.toml

Reparo: add safe-mode in reapro example config file 

---

pump/storage/bench_test.go
pump/storage/storage.go
pump/storage/storage_test.go
pump/storage/vlog_test.go

It still takes about 15 seconds to run.
Make it faster, the new run time is about 6.5 seconds.
Tests 
- Unit test
Code changes
Side effects

pump: Make the pump/storage unit tests faster

---

drainer/schema.go
drainer/server.go

reviewed after https://github.com/pingcap/tidb-binlog/pull/673 
- handle Recover job, don't error in schema by falling to the default case inside `handleDDL`
- fix can't close internally
Note if in the taskGroup.Go if we call s.Close()
it will wait on the taskGroup in the Close() implement
but we are still clock in the closure pass into Go for calling
s.Close(), so it will call Done inside taskGroup and will block in
Wait(), this is a dead lock.
Tests 
- Unit test
run `recover table a` and fail(exec at downstream and the downstream not support) and quit
Code changes
Side effects
- Need to cherry-pick to the …

handle Recover job and fix can't close internally

---

pump/storage/storage.go
pump/storage/storage_test.go

Make `TestCloseAndOpenAgain` -- which is one of the slowest test case --
faster.
We had to wait for about 3 seconds before closing because
`handleSortItems` only save maxCommitTS and handlePointer at most
once per second. But when testing, we don't want to wait for so long.
Make the interval an variable, so that we can override it with shorter
durations in the test case.
Now we are waiting milliseconds instead of seconds.
Tests 
- Unit test
Code changes
Side effects

tests: No need to wait for seconds before closing

---

pkg/sql/sql.go
pkg/sql/sql_test.go

IgnoreDDLError func is missing a ``` ErrKeyNotExists ``` error code in "pkg/sql" module.
Add ```ErrKeyNotExists``` in IgnoreDDLError func.
Tests 
- Unit test
Code changes
Side effects

pkg/sql: add missing error code of IgnoreDDLError

---

cmd/drainer/drainer.toml
drainer/config.go
drainer/syncer.go
drainer/syncer_test.go

add ignore-txn-commit-ts to skip some txn.
use case: for some incompatible DDL, user may handle it manaually and want to skip this binlog, currentlly, usert can only change the checkpoint to skip this,  the process is tedious and prone to error.
add `ignore-txn-commit-ts` support to skip specified commit ts txn
Tests 
- Unit test
config `ignore-txn-commit-ts` and make sure it skip it
Code changes
Side effects

drainer/: Add ignore-txn-commit-ts to skip some txn

---

cmd/drainer/README.md
cmd/pump/README.md
drainer/config.go
drainer/server.go
drainer/translator/kafka.go
pump/config.go

[TOOL-1410](https://internal.pingcap.net/jira/browse/TOOL-1410)
Modify `drainer/server.go`. If user specifies a node-id, drainer ID will be set as this value. If not, drainer will automatically generate a node ID referring to the listening host name and port.
Tests 
- Unit test
* Change the `tests/run.sh:119` from `run_drainer -L debug &`
to `    run_drainer -L debug -node-id binlog:group &`
* Execute `./tests/run.sh` and check `/tmp/tidb-binlog-test/drainer.log`
* Execution result without change `tests/run.sh:119`:
* Execution result after change `tests/run.sh:119`:
Code changes
Side effects

add node-id cmd to specify drainer's node-id

---

pump/server.go

as expected to write fails, make it not a tedious error log
refine log when not in online state
as expected to write fails, make it not a tedious error log
Tests 
- Unit test
Code changes
Side effects

server.go: refine log when not in online state

---

binlogctl/nodes.go
binlogctl/nodes_test.go

`registry.Nodes` is used to get all nodes before searching for the node
with the specified ID.
Use `registry.Node` to look up the specified node ID directly.
The error output for nodes not found is a little different from before,
since the error is logged directly.
Tests 
- Unit test
- Manual test
Code changes
Side effects

binlogctl: Use registry.Node to get a single node directly

---

cmd/drainer/drainer.toml
drainer/config.go
drainer/syncer.go
drainer/syncer_test.go

add ignore-txn-commit-ts to skip some txn.
use case: for some incompatible DDL, user may handle it manaually and want to skip this binlog, currentlly, usert can only change the checkpoint to skip this, the process is tedious and prone to error.
cherry-pick https://github.com/pingcap/tidb-binlog/pull/685
Tests 
- Unit test
Code changes
Side effects

drainer/: Add ignore-txn-commit-ts to skip some txn (#685)

---

pump/storage/storage.go

In some extreme cases, when leveldb write failed, pump server may be entering an infinite loop
Tests 
- No Test

Add metric for batch write kv

---

pump/server.go
pump/storage/sorter.go
pump/storage/sorter_test.go
pump/storage/storage.go

* pump/: Fix block at wait for MaxCommitTS when offline
when offline:
1, ApplyAction change statue to be closing, reject write but accept fake
binlog
2, commitStatus() -> waitSafeToOffline(), we will write a fake binlog
and wait when storage.MaxCommitTS() >= commit ts of the fake binlog
...
after 1, may having some unwritten c-binlog(we will reject the write
request from tidb), and in sorter, block at s.cond.Wait case because no
more any item push.
cherry-pick https://github.com/pingcap/tidb-binlog/pull/701
Tests 
- Unit test
Code changes
Side effects

pump/: Fix block at wait for MaxCommitTS when offline (#701)

---

tests/dailytest/case.go

There are many duplicate code for executing SQLs and exitting on error.
Reuse `mustExec`.
Tests 
Code changes
Side effects

Use mustExec to simplify SQL execution in test cases

---

pump/node.go
pump/server.go

pump server start process:
1. register the node in pd
....
n. listen ports(http and grpc service)
This leads to pump client maybe find an inaccessible pump server in pd(not listen ports yet)
change the pump server start process: first, listen ports and then register the node
Tests 
- Unit test
- No code
Code changes
Side effects
- Need to be included …

Pump: Fix pump server start process

---

arbiter/config.go
arbiter/config_test.go
drainer/config.go
drainer/config_test.go
pkg/util/util.go
pump/config.go
pump/config_test.go
reparo/config.go
reparo/config_test.go

[TOOL-1403](https://internal.pingcap.net/jira/browse/TOOL-1403)
Referral PR: [TiDB#9855](https://github.com/pingcap/tidb/pull/9855/)
cherry-pick: https://github.com/pingcap/tidb-binlog/pull/687
Now func `configFromFile` in `config.go` of **drainer, pump, arbiter, reparo** will make sure that there is no undecoded args in `metaData`. This can help customers check their misspell in the config toml files. Relative tests have been added, too.
Tests 
- Unit test
Code changes
Side effects

Return error when loading some undefined configs from local

---

tests/dailytest/case.go

This PR is a replication of https://github.com/pingcap/tidb-binlog/pull/707. I accidentally forced push to my own branch so it closed...
1. Refine case name in `tests/dailytest/case.go` similar to https://github.com/pingcap/tidb-binlog/pull/667.
2. https://github.com/pingcap/tidb-binlog/pull/705 updated parser which supported `pre_split_regions`. This PR add one test to test whether sql `pre_split_regions` can be parsed in binlog and synced to downstream.
Case name has been refactored and one more test about `pre_split_regions` is added. This test will create a table with `pre_split_regions` and try to insert some data.
Tests 
- Unit test
Code changes
Side effects

refine case name and add split region test

---

pump/storage/metrics.go
pump/storage/storage.go

When the size of metadata(storage with leveldb) grown very large, pump storage gc will be very slowly. The reason for this bug is the `seek` operation in `goleveldb` spend too much time.
we `seek` only one time on the `init` process of GC, instead of `seek` every time before `vlog gc`.
Tests 
- Unit test
Passed
- No code

Avoid repeated called of NewIterator which might be slow

---

arbiter/server.go
arbiter/server_test.go

[TOOL-1488](https://internal.pingcap.net/jira/browse/TOOL-1488)
When loader executes some dmls and meet an error in `loader.Run()`, it will shut down, report an error and stop dealing with chan `loader.input`. But `syncBinlogs` in `arbiter/server.go` will keep on pushing items into `loader.input`, when it get full, function `syncBinlogs` will be blocked and then arbiter will be unable to quit or issue the error.
Add `syncCtx` and `select` in function `syncBinlogs` to avoid blocking.
Tests 
- Unit test
Modified arbiter will quit as we expect.
Code changes
Side effects

fix bug when some error occurs in loader arbiter's syncBinlog may block

---

pump/storage/storage.go

When error happened in loop,  iter may not be released. And when `l0Num >= l0Trigger`, we better release the iter, it may be affect compaction operation.
Tests 
- Unit test
- No code
Code changes
Side effects

fix iter may not be Released in some cases

---

pump/storage/metrics.go
pump/storage/storage.go

When the size of metadata(storage with leveldb) grown very large, pump storage gc will be very slowly. The reason for this bug is the seek operation in goleveldb spend too much time.
cherry-pick #718 and #722
Tests 
- Unit test
- No code
Code changes
Side effects

Avoid repeated calls of NewIterator which might be slow (#718 & #722)

---

drainer/checkpoint/mysql.go

[TOOL-1520](https://internal.pingcap.net/jira/browse/TOOL-1520)
In previous `drainer/checkpoint/mysql.go:Load()` we use `query` to get the checkpoint data but never check the `row.Err()` which may skip some failures but the `checkpoint` is still updated.
Modify `Load()` in mysql checkpoint. Current version will use `queryrow` instead of `query` to avoid missing some errors.
Tests 
- Unit test
Code changes
Side effects

Avoid risk of ignoring failed to read checkpoint

---

pump/storage/storage.go
pump/storage/storage_test.go

we don't have a test case when the total number of kv is large.
I just turn up the total number of kv and gc ts.
and i fix a bug by the way,it will skip a key by mistake when `deleteBatch = 100`.
Tests 
- Unit test

test: add test for metadata gc 

---

cmd/reparo/reparo.toml
reparo/config.go
reparo/reparo.go
reparo/syncer/mysql.go
reparo/syncer/mysql_test.go
reparo/syncer/syncer.go
reparo/syncer/syncer_test.go

[TOOL-1547](https://internal.pingcap.net/jira/browse/TOOL-1547)
Add `worker count` and `txn batch` config for reparo. Users can decide these indecies themselves to change the sync speed of `reparo`.
Expose `worker count` and `txn batch` to config.
Tests 
- Unit test
Code changes
Side effects

reparo/:Add worker-count, txn-batch config

---

pump/server.go

A son PR of https://github.com/pingcap/tidb-binlog/pull/735.
When we try to close pump server, we will cancel `s.ctx` first. But we wish that `storage` will pull storaged binlogs until drainer receives them. Then pump can safely quit. But if we use `s.ctx` for `storage.PullCommitBinlog` it will quit at first and drainer may no longer receive binlog from this pump.
Change `s.ctx` to `context.Background()` and add `s.pullClose` channel to control the closure of `PullBinlogs`. Run `close(s.pullClose)` after `commitStatus`.
Tests 
- Unit test
Code changes
Side effects

fix pump storage quit bug

---

pump/server.go
pump/server_test.go

cherry-pick of https://github.com/pingcap/tidb-binlog/pull/739
When we try to close pump server, we will cancel `s.ctx` first. But we wish that `storage` will pull storaged binlogs until drainer receives them. Then pump can safely quit. But if we use `s.ctx` for `storage.PullCommitBinlog` it will quit at first and drainer may no longer receive binlog from this pump.
Change `s.ctx` to `context.Background()` and add `s.pullClose` channel to control the closure of `PullBinlogs`. Run `close(s.pullClose)` after `commitStatus`.
Tests 
- Unit test
Code changes
Side effects

fix pump pull pop bug while closing pump

---

tests/dailytest/case.go
tests/run.sh

updatePKUK output a lot of logs for retrying to generate unused PKs.
Record free PKs explicitly to avoid retrying.
Tests 
Code changes
Side effects

tests: Rewrite updatePKUK to avoid outputing a lot of messages about generating PKs

---

cmd/reparo/reparo.toml
reparo/config.go
reparo/reparo.go
reparo/syncer/mysql.go
reparo/syncer/mysql_test.go
reparo/syncer/syncer.go
reparo/syncer/syncer_test.go

cherry-pick https://github.com/pingcap/tidb-binlog/pull/742
[TOOL-1547](https://internal.pingcap.net/jira/browse/TOOL-1547)
Add `worker count` and `txn batch` config for reparo. Users can decide these indecies themselves to change the sync speed of `reparo`.
Expose `worker count` and `txn batch` to config.
Tests 
- Unit test
Code changes
Side effects

reparo/:Add worker-count, txn-batch config (#742)

---

drainer/syncer.go

In `syncer.run` if we quit directly channel `syncer.closed` will not be closed and drainer will get blocked while closing.
Change `return` to `break ForLoop`
Tests 
- Unit test
Code changes
Side effects

optimize drainer syncer quit

---

pump/server_test.go

Refine Pump server test to avoid fault in `TestStartPumpServer`.
Change `string` to `strconv.FormatInt`.
Tests 
- Unit test
Code changes
Side effects

fix pump server_test

---

pump/storage/storage.go

Call CleanUp cmp for ddl binlog too.
may get the txn status from tikv or skip the binlog.
Tests 
- Unit test
Code changes
Side effects

storage.go: Make query tikv for ddl too

---

pump/storage/sorter.go
pump/storage/storage.go
pump/storage/vlog.go

in pull binlog, if start ts is greater than max commit ts, pump may panic because goleveldb's bug https://github.com/syndtr/goleveldb/issues/224 
add a check in storage
and update some log by the way
Tests 
- Manual test

pump.Storage: fix possible panic if start ts is greater than max commit ts when pull binlog 

---

pump/storage/storage.go

in pull binlog, if start ts is greater than max commit ts, pump may panic because goleveldb's bug syndtr/goleveldb#224
copy some code from https://github.com/pingcap/tidb-binlog/pull/758

pump.Storage: fix possible panic if start ts is greater than max commit ts when pull binlog

---

drainer/server.go
go.mod
go.sum
pump/node.go
pump/server.go

After https://github.com/pingcap/tidb/pull/12055 tidb upgrade grpc to 1.23, the client can't no longer connect to pump server.
upgrade to gRPC to 1.23 from 1.17.
change cmux how to match for gRPC, see:
soheilhy/cmux#64
https://github.com/soheilhy/cmux#limitations
this still compatible with the older version tidb(with gRPC client 1.17).
Tests 
- Unit test
run with 1.23 and 1.17 gRPC client version tidb
Code changes
Side effects

upgrade grpc to 1.23

---

drainer/merge.go

when drainer receives duplicate binlog, it will output an error log like `binlog's commit ts less than the last ts`
Change log level to `Warn` for duplicate binlog
Tests 
- Unit test
Code changes
Side effects

drainer: refine log when meeting duplicate binlog

---

pump/storage/storage.go

cherry-pick #757 
Note: just drop the `if pbinlog.GetDdlJobId() == 0 ` condition and update log  at last line.
Tests 
Code changes
Side effects

storage.go: Make query tikv for ddl too (#757)

---

go.mod
tools/check/go.mod

After upgrading to Go 1.13, a version line is appended to go.mod whenever we try to build the project.
Just commit it so that we don't have to revert the changes each time.
Tests 
- No code
Code changes
Side effects

Commit Go 1.13 changes to go.mod

---

pump/storage/log.go
pump/storage/vlog.go

We only measurer the time taken to write a batch of binlogs at the top level.
But we have no other measurementt to help us figure out which step is taking up most of the time.
Add 3 metrics:
1. Time taken to write a buf
1. Time taken to rotate
1. Time taken to fsync
Tests 
- Unit test
Code changes
Side effects

pump/storge: Measure time taken to write to disk, to rotate and fsync

---

binlogctl/config.go
binlogctl/nodes.go
binlogctl/nodes_test.go
cmd/binlogctl/main.go
tests/_utils/check_status

Some users complain that pump/drainer nodes that have been turn off still appears in the list.
Hide `offline` nodes by default, only show them when `-show-offline-nodes` is set.
Tests 
- Manual test
I set a drainer to `offline` and then check with `binlogctl drainers`.
Code changes
Side effects

binlogctl: Only show offline nodes when explicitly told so

---

drainer/config.go
drainer/server.go
tests/dailytest/case.go
tests/kafka/run.sh
tests/reparo/run.sh
tests/restart/run.sh
tests/status/run.sh

easy deploy for starting at the latest timestamp
drainer/*: get the latest timestamp from PD when initial-commit-ts is -1
Tests 
Code changes
Side effects

drainer/*: get latest timestamp from pd when initial-commit-ts is -1

---

drainer/config.go
drainer/config_test.go
pkg/filter/filter.go
pkg/filter/filter_test.go

Fix panic of empty value in filter config
Verify config about filters
Fix panic of empty value in filter config
Verify config about filters
Tests 
- Unit test
Code changes
Side effects

Fix panic of empty value in filter config

---

drainer/config.go
drainer/config_test.go
pkg/filter/filter.go
pkg/filter/filter_test.go

Fix panic of empty value in filter config
Verify config about filters with empty schema or table name.
cherry-pick #799 
Fix panic of empty value in filter config
Verify config about filters with empty schema or table name.
Tests 
- Unit test
Code changes
Side effects

Fix panic of empty value in filter config (#799)

---

drainer/syncer.go

we start `Syncer` goroutine in `drainer`
```
s.tg.GoNoPanic("syncer", func() {
defer func() { go s.Close() }()
if err := s.syncer.Start(); err != nil {
log.Error("syncer exited abnormal", zap.Error(err))
}
})
```
if `s.syncer` panic (like kafka producer panic), `s.syncer.Start()` would exit directly and  the logics will happen 
* drainer calls `s.syncer.Close()` in `s.Close()`
* `s.syncer.Close()` would wait `<- s.syncer.closed` take effetcs,
* but `s.syncer.closed` only can be closed in `s.syncer.run()`
add `defer close(s.syncer.closed)` in `s.syncer.run()`

fix deadlock while drainer.Syncer panic

---

pkg/loader/util.go
pkg/loader/util_test.go

add a log when table not found
when table not found in `getTableInfo` function, we can't know which table was unfound.
Tests 
- Unit test
- Integration tes

loader: add a log when table not found

---

Makefile

Fix #828
Remove the check.
Tests 
- Manual test
Check that `make` works with or without `$GOPATH`.

*: Fix #828, GOPATH is no longer required to build binlog projects

---

arbiter/server.go
arbiter/server_test.go

we can‘t ensure that the message in kafka is unique, so we need discard the repeated kafka message
Tests 
- Unit test

arbiter: discard the repeated kafka message

---

tests/run.sh

latest version tidb fails to start up in tests/
config txn-total-size-limit in tests
the latest tidb version has enlarge this and reject to start up if
txn-total-size-limit > 100 * (1<<20)
relate code:
295:	TxnTotalSizeLimit   uint64  `toml:"txn-total-size-limit" json:"txn-total-size-limit"`
724:		return fmt.Errorf("txn-total-size-limit should be less than %d with binlog enabled", 100<<20)
727:		return fmt.Errorf("txn-total-size-limit should be less than %d", 10<<30)
Tests 
Code changes

config txn-total-size-limit in tests

---

drainer/relay/relayer_test.go
drainer/sync/mysql_test.go
drainer/sync/syncer_test.go
drainer/translator/kafka_test.go
drainer/translator/mysql_test.go
drainer/translator/pb_test.go
drainer/translator/testing.go

Fix a typo in a struct name
Genrator -> Generator
Tests 
- Unit test

drainer: Fix typo in struct name

---

pump/storage/storage.go
pump/storage/storage_test.go

The DDL `c-binlog`s sent from TiDB include `ddl query`, `ddl job id`. But the `c-binlog` queried from TiKV doesn't include this info. Unfortunately, pump never read the `ddl query`, `ddl job id` from `p-binlog`. So a DDL `p-binlog` will be ignored when the c-binlog queried from TiKV.
fix: #851
Copy the `ddl query`, `ddl job id` from `p-binlog` to `c-binlog`.
Tests 
- Unit test

Bug fix: a DDL p-binlog will be ignored when the c-binlog queried from TiKV

---

pump/storage/storage.go
pump/storage/storage_test.go

The DDL `c-binlog`s sent from TiDB include `ddl query`, `ddl job id`. But the `c-binlog` queried from TiKV doesn't include this info. Unfortunately, pump never read the `ddl query`, `ddl job id` from `p-binlog`. So a DDL `p-binlog` will be ignored when the c-binlog queried from TiKV.
fix: #851
cherry-pick #852
Copy the `ddl query`, `ddl job id` from `p-binlog` to `c-binlog`.
Tests 
- Unit test

Bug fix: a DDL p-binlog will be ignored when the c-binlog queried from TiKV(#852)

---

tests/dailytest/case.go

Sometimes the goroutine that drops columns runs before we insert the row with all columns and cause error.
Make sure the insertion happens before updating and column dropping starts.
Tests 

tests: Make sure the INSERT is executed before we starts droppling cols

---

cmd/drainer/drainer.toml
drainer/config.go
drainer/relay/reader.go
drainer/relay/reader_test.go
drainer/relay/relayer_test.go
pkg/binlogfile/binlogger.go

Define `relay.Reader` that can read all relay logs, and return parsed transactions one by one. 
The last checkpoint should be passed to `Reader` after bootstrap so that transactions already synced last time should be ignored. But `binlogger` is not capable to write and read `CommitTS`, so it may be optimized in another PR.
Define `relay.Reader` to read all relay logs and parse them to transactions.
Tests 
- Unit test
Code changes
Side effects

drainer: support reading from relay log

---

pkg/loader/load.go

`loader` try to query the latest `TableInfo` from the downstream db after executing a DDL.
Sometimes there's no DMLs depending on the table in between two DDLs, it would be wasteful to query everytime.
Just invalidate the cached `TableInfo`, the next DML that needs this info would call `getTableInfo` and query the latest info.
Tests 
- Unit test

drainer: Clear the cache instead of refreshing after DDL to avoid unnecessary queries

---

binlogctl/config.go
binlogctl/encrypt.go
cmd/binlogctl/main.go
cmd/drainer/drainer.toml
drainer/config.go
drainer/config_test.go
drainer/sync/util.go
pkg/encrypt/encrypt.go
pkg/encrypt/encrypt_test.go

pick #857
* Add encrypt password support
also add a command to binlogctl, usage example:
./binlogctl -cmd encrypt -text aaa

Add encrypt password config support (#857)

---

scripts/groovy/binlog_ghpr_integration.groovy

in https://github.com/pingcap/tidb-binlog/pull/857/commits/32ee5e88ff3a4d2ddc74da293a5f862718b4d803, we add a 60min idle to investigate CI problem, but for normal CI situation we should release resource quickly.
set idle back to 0
Tests 
- Unit test
Code changes
- n/a
Side effects
- n/a
- n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb-binlog/869)

scripts: release pod resource after CI test

---

cmd/drainer/drainer.toml
drainer/sync/mysql.go
drainer/sync/mysql_test.go
drainer/sync/util.go
pkg/loader/load.go
pkg/loader/load_test.go

allow when the column number of downstream table mismatch with current schema.
For the case bidirectional replication, we will execute the DDL at one side, for add or drop column
the column number will mismatch.
cluster A <-> cluster B
- drop column of table `t` at cluster A
- some DML of table `t` at cluster B will miss the column dropped compared to cluster A
Add a config item `sync-mode`
when setting SyncPartialColumn will allow mismatch column number
and relax sql mode by removing STRICT_TRANS_TABLES.
Tests 
- Unit test
Code changes
Side effects

Add sync mode config to allow mismatch column number

---

cmd/drainer/drainer.toml
drainer/config.go
drainer/loopbacksync/loopbacksync.go
drainer/loopbacksync/loopbacksync_test.go
drainer/sync/mysql.go
drainer/sync/mysql_test.go
drainer/sync/syncer_test.go
drainer/sync/util.go
drainer/syncer.go
drainer/syncer_test.go
pkg/loader/executor.go
pkg/loader/load.go
pkg/loader/load_test.go
pkg/loader/model.go
pkg/loader/model_test.go

cherry pick #879 #867 
cherry pick #879 #867 
Add sync mode config (#867)
allow when the column number of downstream table mismatch with current schema.
For the case bidirectional replication, we will execute the DDL at one side, for add or drop column
the column number will mismatch.
cluster A <-> cluster B
drop column of table t at cluster A
some DML of table t at cluster B will miss the column dropped compared to cluster A
binlog loop back sync (#879)
In the AA dual activity scenario, there is data write (DML) on both sides. The data of tidb cluster on both sides needs to be synchronized with each other，but avoid loopback synchronization，and ddl is only writed one side.
add three variables in drainer.toml as identification to confirm need sync ddl or not and need set sync mark …

binlog loop back sync

---

cmd/drainer/drainer.toml
drainer/relay/relayer.go
drainer/sync/pb.go
drainer/sync/syncer_test.go
drainer/sync/util.go
drainer/syncer.go
pkg/binlogfile/binlogger.go
pkg/binlogfile/binlogger_test.go

Enable drainer to purge old incremental backup data on disk.
1. Add a `retention-time` config to specify how long binlog files should be kept in drainer. Backward-compatibility is maintained by treating non-positive values of `retention-time` as *no GC*.
1. Currently `retention-time` is of type `int`, which is consistent with the pump `GC` configuration. We may later introduce `p8s` style time format for both `GC` and `retention-time` and use days as the default unit to maintain backward-compatibility.
Tests 
- Unit test
Code changes
The `GC` method is changed to two new methods `GCByTIme` and `GCByPos`.

drainer: Fix #724, Enable drainer to purge old incremental backup data on disk

---

drainer/sync/mysql.go
drainer/sync/syncer.go
drainer/syncer.go
drainer/translator/mysql.go
drainer/translator/mysql_test.go
pkg/loader/executor.go
pkg/loader/executor_test.go
pkg/loader/load.go
pkg/loader/load_test.go
pkg/loader/model.go
pkg/loader/model_test.go
reparo/syncer/mysql_test.go
reparo/syncer/print_test.go
reparo/syncer/translate_test.go

In bidirectional replication
cluster A <-> cluster B
only do and replicate DDL in A
- in B will filter all DDL and will never refresh the table info in pkg/Loader
- we will not know the schema is changed while replicating data from B to A if a DDL is applied on A and not having replicated to B. A sample case:
* drop a column `c81` on table `auto1` (apply on A)
* apply some DML on B and replicate to cluster A will failed for we specified the column `c81` to insert cause we have not learned that the Shema is changed on A.
- refresh table info even if we filter the ddl on B(make an empty query force loader to refresh now)
- try refresh table info if failed to exec the dml for some error (column mismatch now)
- always  use the values pass into Loader to construct the SQL(compared to the …

Fix current DML&DDL corner case for bidirectional replication 

---

cmd/drainer/drainer.toml
drainer/checkpoint/checkpoint.go
drainer/checkpoint/file.go
drainer/checkpoint/file_test.go
drainer/checkpoint/mysql.go
drainer/checkpoint/mysql_test.go
drainer/checkpoint/util.go
drainer/checkpoint/util_test.go
drainer/config.go
drainer/relay.go
drainer/relay/reader.go
drainer/relay/reader_test.go
drainer/relay/relayer.go
drainer/relay_test.go
drainer/server.go
drainer/sync/mysql.go
drainer/sync/syncer.go
drainer/syncer.go
drainer/syncer_test.go
pkg/util/util.go

support to recover at startup by relay log. 
follows #847 #849 
- add a status in checkpoint
- we can learn from the status that there are dirty data written into downstream behind commit ts or not.
- group the config items about relay
- remove the `relay-read-buf-size`
- rename `relay-log-size` to `max-file-size`
- make relay.Reader return the origin format  directly
- this will be more flexible by the user of the reader
- feed downstream by relay log at startup if need.
- mainly implement in `drainer/relay.go`
- only fails to init the pd client will try this or just assume the upstream cluster is normal and works like before.
Tests 
- Unit test
- kill -9 drainer & pd while insert data into upstream
- check status is Running
- startup …

feed downstream by relay log at startup if need

---

arbiter/server.go
arbiter/server_test.go
cmd/drainer/drainer.toml
drainer/config.go
drainer/relay.go
drainer/sync/mysql.go
drainer/sync/syncer_test.go
drainer/sync/util.go
pkg/loader/example_loader_test.go
pkg/loader/util.go
reparo/syncer/mysql.go
reparo/syncer/mysql_test.go

fix #887 
Add an according configure part `syncer.to.security`
use [RegisterTLSConfig](https://godoc.org/github.com/go-sql-driver/mysql#RegisterTLSConfig) to  registers a custom `tls.Config` to be used with sql.Open
Tests 
* enable TLS in drainer, fails to connect  TiDB without enabling TLS.
* after enable TLS, drainer success to connect to TiDB.
relate docs: https://pingcap.com/docs-cn/stable/how-to/secure/enable-tls-clients/

Support TLS to connect mysql/TiDB

---

cmd/drainer/drainer.toml
drainer/sync/kafka.go
drainer/sync/util.go
tests/binlog/drainer.toml

Improve configuration for kafka syncer:
Add kafka-client-id in drainer.toml to config kafka client.id property.
Drainer should support kafka clientID property https://github.com/pingcap/tidb-binlog/issues/900

drainer: add KafkaClientID in DBConfig

---

drainer/loopbacksync/loopbacksync.go
drainer/loopbacksync/loopbacksync_test.go
pkg/loader/executor.go
pkg/loader/load.go
pkg/loader/model.go
pkg/loader/model_test.go

first commit: fix https://github.com/pingcap/tidb-binlog/issues/910
second commit: Refactor loopback sync
put the main logic together in drainer/loopbacksync. this should look more clear, also simplify some func. and distinct the metrics of time need to update mark table from other replicate sql, this can help us know whether it's too slow to update mark table and that will be a bottle net.
a metrics example:
Tests 
- Unit test
sett https://github.com/july2993/bitest#bitest-dml test  bi-replicate clusters.
Code changes
Side effects

fix initMarkTable failed case not quit normally and refactor

---

pkg/loader/model.go

fix unstable test:
the column order in the update sql in the indeterministic order and the test code may fail sometimes.
```
[2020-03-02T10:02:48.916Z] [2020/03/02 18:02:48.034 +08:00] [ERROR] [executor.go:111] ["Exec fail, will rollback"] [query="UPDATE `test`.`t1` SET `b` = ?,`c` = ?,`a` = ? WHERE `a` = ? AND `b` = ? AND `c` = ? LIMIT 1"] [args="[\"test\",\"abc\",1,1,\"test\",\"test\"]"] [error="ExecQuery 'UPDATE `test`.`t1` SET `b` = ?,`c` = ?,`a` = ? WHERE `a` = ? AND `b` = ? AND `c` = ? LIMIT 1', arguments do not match: argument 0 expected [int64 - 1] does not match actual [string - test]"] [stack="github.com/pingcap/log.Error\n\t/go/pkg/mod/github.com/pingcap/log@v0.0.0-20191012051959-b742a5d432e9/global.go:42\ngithub.com/pingcap/tidb-binlog/pkg/loader.(*tx).autoRollbackExec\n\t/home …
```

Make the column order deterministic

---

cmd/drainer/drainer.toml
drainer/sync/kafka.go
drainer/sync/util.go
tests/binlog/drainer.toml

Improve configuration for kafka syncer:
Add kafka-client-id in drainer.toml to config kafka client.id property.
cherry-pick from #902 
Drainer should support kafka clientID property #900

drainer: add KafkaClientID in DBConfig (#902)

---

go.sum
pkg/security/security.go
pkg/security/security_test.go

support reload cluster/downstream  TLS cert/key.
CA still can not be hot-reload now
preliminary of #891 
Reload cert/key of tls for new connection
for the pd client and kv client need to update dep version of pd/db, it will be handle by the client.
but this pr enough for reload certification used to connecting downstream db.
- support reload cluster/downstream TLS cert/key, CA still can not be hot-reload now
Tests 
- Unit test
Code changes
Side effects

Reload cert/key for every new conn

---

cmd/drainer/drainer.toml
cmd/pump/pump.toml
pkg/security/security.go
tests/_utils/run_drainer
tests/_utils/run_pump
tests/run.sh

fix issue https://github.com/pingcap/tidb-binlog/issues/930
Allow pump and drainer add TLS certificate CN validation
add `VerifyPeerCertificate` function for tls
Tests 

support common name check for tls

---

cmd/drainer/drainer.toml
cmd/pump/pump.toml
pkg/security/security.go
tests/_utils/run_drainer
tests/_utils/run_pump
tests/run.sh

cherry-pick #934 
fix issue https://github.com/pingcap/tidb-binlog/issues/930
Allow pump and drainer add TLS certificate CN validation
add `VerifyPeerCertificate` function for tls
Tests 

support common name check for tls(#934)

---

drainer/schema.go
tests/filter/run.sh

ref https://github.com/pingcap/tidb-binlog/pull/941
skip wrongly write ActionUpdateTiFlashReplicaStatus job
after https://github.com/pingcap/tidb/pull/16049 there's no any ActionUpdateTiFlashReplicaStatus job that will be written.
Tests 
create table t(id int);
ALTER TABLE t SET TIFLASH REPLICA 3 LOCATION LABELS "rack", "host", "abc"; // model.ActionSetTiFlashReplica
curl -X POST -d '{"id":45,"region_count":3,"flash_region_count":3}' https://127.0.0.1:10080/tiflash/replica // model.ActionUpdateTiFlashReplicaStatus
performance write on table t and check can still replicate. - No code
Code changes
Side effects

skip wrongly write ActionUpdateTiFlashReplicaStatus job

---

drainer/config.go
drainer/server.go
pump/config.go
pump/server.go

Fix #936
When TLS is enabled, the logs of drainer contains http:
log https instead of HTTP when enabling TLS.
Also, log advertise addr instead of listen addr
Tests 
start and check the log
Code changes
Side effects

Refine log when enable tls

---

drainer/config.go
drainer/config_test.go
drainer/util.go
pump/config.go
pump/server.go

tidb support big transaction, and the binlog's size may bigger than 1G, so need to update the grpc's max message size.
update the max message size to `math.Int32`(2G)
Tests 
- Unit test

.*: update max message size for grpc

---

drainer/translator/kafka.go

Fix unknown type for mediumint
Handle `mediumint` type and write value as IntValue or UintValue instead of reaching the default case:
https://github.com/pingcap/tidb-binlog/blob/dcc904712318c1a2d2a567ee99a7bfeb742809ca/drainer/translator/kafka.go#L275
Tests 
insert a `mediumint` type data and check data.
Code changes
Side effects
- Fix unknown type of mediumint when transforming to the format writer to Kafka.

Fix unknown type for mediumint

---

drainer/translator/pb.go
drainer/translator/pb_test.go
tests/reparo/config.toml
tests/reparo/run.sh
tests/reparo/sync_diff_inspector.toml

fix #955
db name is not quoted when we format the DDL, so when it contains some reserved characters，we will fail to parse the DDL.
quote the db name when formatting the DDL.
Tests 
- Unit test
Code changes
Side effects
- Fix reparo fails to parse DDL when the database name contains the reserved characters.

Fix not quote db name in file data ddl

---

tests/run.sh

Fix fails to start up tidb in integration test
Specify the status port of tidb
The old version will ignore the error if fails to listen on the status
port, now it will reject to start.
Tests 
- No Release note.

Specify status port of tidb in tests

---

pump/node.go
tests/dailytest/case.go

Fix notify drainer not enable tls
Fix notify drainer not enable tls
Tests 
check the new started pump in /tests/restart/run.sh do can be started.
- Fix pump notify drainer not enable TLS.

Fix notify drainer not enable tls

---

drainer/translator/kafka.go
drainer/translator/kafka_test.go
drainer/translator/testing.go

fix #932
put the mutations of the same table in one `Table` struct
Tests 
- Unit test
Code changes
Side effects
- Fix multi rows of the same table split into multi-table structure in the downstream format

Fix multi rows of same table split into multi table in the downstream format

---

pkg/loader/util.go
tests/dailytest/case.go
tests/kafka/kafka.go

After https://github.com/pingcap/tidb/pull/17102 unable to replicate auto random table.
the pr add a session system var `allow_auto_random_explicit_insert`, default is false, must enable for insert value explicit, or can't
replicate. This is unfriendly for replication or restores tools. 
the test is disabled in #971 temporarily.
Enable `allow_auto_random_explicit_insert` if ths sys var is supported. 
Tests 
test with version support and not support this var.
- Enable `allow_auto_random_explicit_insert` automatic.

Enable allow_auto_random_explicit_insert if it's suppported

---

drainer/metrics.go
drainer/sync/mysql.go
drainer/sync/util.go
go.mod
go.sum
pkg/loader/load.go

test by run at upstream:
```
sysbench  oltp_insert --mysql-host=127.0.0.1 --mysql-user=root --mysql-password= --mysql-port=4000 --tables=10 --table-size=1000000 --threads=64 --create_secondary=off --report-interval=10 prepare
```
and start cluster locally and a MySQL as downstream
drainer config:
```
worker-count = 256
txn-batch = 200
```
master:
dml number per worker is only 10~20, the load of MySQL is low. about 100% cpu
after inc the limit in-memory dml:
mysql about 600% cpu
using merge = true:
```
[syncer.to]
merge = false
```
- No Release note.

expose merge mode by config and add metrics

---

cmd/drainer/drainer.toml
drainer/checkpoint/mysql.go
drainer/checkpoint/mysql_test.go
drainer/checkpoint/util.go
drainer/config.go
drainer/sync/util.go
drainer/util.go

Fix not using tls when saving checkpoint.
when syncer.to.security is enable.
the db create for replicating data will enable tls, but the db for saving checkpoint is not.
enable tls for the db saving checkpoint too.
- Fix not using TLS when saving checkpoint

Fix not using tls when saving checkpoint

---

drainer/sync/syncer.go
drainer/syncer.go
pkg/loader/load.go
tests/filter/run.sh

Add the commit ts in the exec ddl failed log
Add the commit ts in the exec ddl failed log
before:
```
[2020/07/30 10:55:44.726 +08:00] [INFO] [schema.go:452] ["Finished dropping column"] [job="ID:74647, Type:drop column, State:synced, SchemaState:none, SchemaID:1926, TableID:64516, RowCount:0, ArgLen:0, start time: 2020-06-18 13:31:13.836 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2020/07/30 10:55:44.729 +08:00] [INFO] [syncer.go:445] ["add ddl item to syncer, you can add this commit ts to `ignore-txn-commit-ts` to skip this ddl if needed"] [sql="recover table ads_rpt_app_new_remain_stat"] ["commit ts"=418180461697695746]                          [2020/07/30 10:55:49.901 +08:00] [ERROR] [load.go:687] ["exec failed"] [sql="recover table ads_rpt_app_new_remain_stat"] …
```

Add the commit ts in the exec ddl failed log

---

pkg/util/duration.go
pkg/util/duration_test.go
pump/config.go
pump/config_test.go
pump/server.go
pump/server_test.go

cherry-pick #996 to release-3.0
---
resolve https://github.com/pingcap/tidb-binlog/issues/994
Support gc time for "8m", "7h". If no unit is specified, gc duration will use day as unit as before. 
It should be noticed that the max time duration unit that supported in golang is hour "h". 
https://github.com/golang/go/issues/11473
https://github.com/golang/go/issues/17767
Tests 
- Unit test
Code changes
- support go time duration format for pump GC configuration

support go time package format gc time (#996)

---

drainer/schema.go
drainer/syncer.go

fix #1015
`lock/unlock table` in TiDB is an unfinished feature, skip these DDL jobs in drainer to avoid interruption.
ignore `ActionLockTable` and `ActionUnlockTable` jobs.
Tests 
- Unit test
1. set `enable-table-lock: true` for TiDB
2. observe drainer can ignore `lock/unlock table` jobs and continue to run
Code changes
Side effects
- No Release note.

drainer: skip lock/unlock table DDL

---

go.mod
go.sum
pump/storage/storage.go

fix #1024
- check `status.TTL() > 0` before check `status.IsCommitted()`. if `status.TTL() > 0`, it means the txn's lock is still valid (neither commit nor rollback)
Tests 
- Unit test
- add `sleep` before `commit` in TiDB as the patch in #1024 (but do not modify `MaxTxnTTL`)
- check no data lost in the downstream
Code changes
Side effects
- Fix the problem that the data of long-time transactions may be lost

pump: check txn TTL before check IsCommitted

---

drainer/checkpoint/checkpoint.go
drainer/checkpoint/file.go
drainer/checkpoint/file_test.go
drainer/checkpoint/mysql.go
drainer/checkpoint/mysql_test.go
drainer/relay.go
drainer/relay_test.go
drainer/sync/syncer.go
drainer/syncer.go

Fix #1032 
save schemaVersion to checkpoint.
with amend txn enabled. `prewrite.SchemeVersion` could out of date.
so when drainer restart, we need to compare `checkpoint'SchemaVersion` and `prewrite.SchemaVersion`.
Tests 
Release note
- Fix the issue that when amend txn enabled. Drainer chooses the wrong schema version of DDL to generate the wrong SQL.

ddl: save checkpoint with schemaVersion

---

tests/dailytest/case.go

workaround test case failure caused by https://github.com/pingcap/tidb/issues/23235
add clustered
Tests 
- Unit test
Code changes
- only test
Side effects
- n/a
- Need to cherry-pick to the release branch 5.0

fix daily test case failure caused by auto_random

---

drainer/translator/translator.go
tests/dailytest/case.go

closes #1042
introduced by #1040
`DecodeOne` only decode column as Raw datum...so date/datetime...will be judged as int
so it make new added test case in PR fail
need call tablecodec to Unflatten raw datum to "real" datum
Tests 
- Unit test
Code changes
- n/a
Side effects
- n/a
- Fix clustered index table replica fail for some type columns

drainer: fix datetime/time clustered index column replication error

---

drainer/translator/translator.go
tests/dailytest/case.go

close https://github.com/pingcap/tidb/issues/24890
for new collation, pk column will be sortedKey(suitable for CI compare rule), row-column will restore raw data
use row's column instead of pk's column if row's column exists
Tests 
- Unit test
Code changes
- n/a
Side effects
-  n/a
- n/a
- Fix clustered index table replica wrong value for collation PK

drainer: fix collation clustered pk as wrong value

---

drainer/pump_test.go
tests/run.sh

Signed-off-by: nolouch <nolouch@gmail.com>
integration test always failed with TLS auth failed.
ref https://github.com/pingcap/tidb-binlog/issues/1049
Tests 
- Unit test

test: make ca's CN not same with host's CN

---

arbiter/config_test.go
binlogctl/meta.go
binlogctl/meta_test.go
cmd/arbiter/main.go
drainer/checkpoint/file.go
drainer/config_test.go
drainer/server_test.go
go.mod
go.sum
pkg/binlogfile/binlogger_test.go
pkg/binlogfile/file_test.go
pkg/file/lock_test.go
pkg/security/security.go
pkg/security/security_test.go
pkg/util/util.go
pump/config_test.go
pump/node.go
pump/node_test.go
pump/server_test.go
pump/storage/log_test.go
pump/storage/vlog.go
reparo/config_test.go
tools/check/go.mod

Fix #1043 
Update go version to 1.16
.. as well as replace usage of `ioutils` which deprecated in Go 1.16 and `ioutil2` which is lack of maintenance.
No release note.

Update go & replace ioutils

---

tests/reparo/sync_diff_inspector.toml
tests/restart/sync_diff_inspector.toml

In order to depend on the newest `sync_diff_inspector` we need to remove the outdated config field `tidb-instance-id` from sync_diff's config
Tests 
Code changes
Side effects
Release note

test: remove outdated tidb-instance-id

---

drainer/config.go
drainer/config_test.go
drainer/relay.go
drainer/sync/mysql.go
drainer/sync/syncer_test.go
drainer/sync/util.go
pkg/loader/util.go
pkg/util/duration.go

When we meet some DDL that will cost a lot of time, `readTimeout` setting to `1m` won't be enough.
add configuration for read-timeout in drainer configuration.
Tests 
- Unit test
Code changes
- Make ReadTimeout for `sql.DB` configurable by `[syncer.to.read-timeout]`

drainer/syncer: add configuration for read-timeout

---

pkg/loader/load.go

close #1087 
nil the txns and dmls slice so golang can gc the big txn
- fix drainer memory leak after a big transaction

loader: clear txns and dmls buffer to free memory

---

reparo/syncer/util.go
reparo/syncer/util_test.go
tests/dailytest/db.go
tests/reparo/binlog.go

close https://github.com/pingcap/tidb-binlog/issues/1096
in https://github.com/pingcap/tidb-binlog/pull/655, drainer will write Uint64 datum for mysql bit type. align reparo's behaviour
Tests 
- Unit test
Code changes
Side effects

reparo: fix can't decode bit type data

---

drainer/schema.go
tests/cache_table/drainer.toml
tests/cache_table/run.sh

Issue Number: close https://github.com/pingcap/tidb/issues/31105
Actually, this PR want to add an integration test to make sure `alter table cache` works with the tools.
It's ignored in the TiDB side already .
For testing of this feature https://github.com/pingcap/tidb/issues/25293
Tests 
- Unit test
- No code
Code changes
Side effects
- Need to be included in the …

drainer: skip 'alter table cache|nocache' DDL jobs

---

drainer/syncer.go

Issue Number: ref #1129
add SyncDDL switcher to the process  that is whether drainer server should stop when non 'truncate table **' statement sync to drainer.
Tests 
- Unit test
- No code
Code changes
Side effects

fix sync-ddl control

---

pkg/loader/model.go

Issue Number: ref #1131 
escape single quote.
Tests 
- Unit test
- No code
Code changes
Side effects

drainer: escape quote in value of column

---

drainer/sync/kafka.go
drainer/sync/kafka_test.go

Issue Number: close https://github.com/pingcap/tidb-binlog/issues/1136
Add `ackWindow` to handle success message from `AsyncProducer` in order. `ackWindow` is a sliding window
that ensure in-order delivery success item. It appends unacked commit ts on the window rightmost  and pop ready acked item from the window leftmost. If the first item is unacked, it doesn't delivery anything.
Tests 
- Unit test
Side effects
- sync/kafka: handle success messages in order

sync/kafka: handle success messages in order

---

drainer/sync/mysql.go
drainer/translator/mysql.go
drainer/translator/oracle.go
drainer/translator/pb.go
go.mod
go.sum
pkg/loader/executor.go
pkg/loader/executor_test.go
pkg/loader/load.go
pkg/loader/load_test.go
pkg/loader/model.go
pkg/loader/model_test.go
pkg/loader/util.go

Issue Number: ref #1157
Using prepare statement method ,when access to oracle
Tests 
- Unit test
- No code
Code changes
Side effects

drainer:sync lob data to oracle

---

drainer/pump.go
drainer/sync/kafka.go
drainer/sync/mysql.go
drainer/sync/mysql_test.go
drainer/sync/oracle.go
drainer/sync/oracle_test.go
drainer/sync/pb.go
drainer/sync/syncer.go
drainer/sync/syncer_test.go
drainer/syncer.go
drainer/translator/kafka.go
drainer/translator/mysql.go
drainer/translator/mysql_test.go
drainer/translator/oracle.go
drainer/translator/pb.go
drainer/translator/translator.go
pump/server.go
pump/server_test.go
pump/storage/storage.go
pump/storage/storage_test.go
tests/binlog/run.sh
tests/dailytest/case.go

Issue Number: close https://github.com/pingcap/tidb-binlog/issues/1159
Adjust drainer's timestamp data to downstream's timezone for mysql/tidb.
Tests 
- Unit test
Code changes
Side effects
- None
- fix the bug that drainer writes incorrect time data when drainer and downstream database are not in a seem time zone

drainer/translater: fix the bug that drainer writes incorrect time data

---

pkg/loader/model.go
pkg/loader/model_test.go
pkg/loader/util.go
pkg/loader/util_test.go

Issue Number: ref #1164
when table defined the char type column, rtrim function will be used in sql
Tests 
- Unit test
- No code
Code changes
Side effects

drainer: rtrim char type column in sql

---

drainer/util.go
pump/config.go
tests/cache_table/run.sh

Issue Number: close https://github.com/pingcap/tidb-binlog/issues/1152
See https://github.com/pingcap/tidb-binlog/issues/1152#issuecomment-1216233918, add 4MB buffer for max grpc message size.
Tests 
- Unit test
Test playground with compressor, works correctly.
- fix drainer can't send request correctly to pump when set compressor=gzip

*: fix drainer can't send request correctly to pump when set compressor=gzip

---

drainer/binlog_item.go
drainer/loopbacksync/loopbacksync.go
drainer/sync/mysql_test.go
drainer/sync/oracle_test.go
drainer/sync/syncer_test.go
drainer/translator/oracle_test.go
pkg/loader/load.go
pkg/loader/util.go
pkg/sql/sql.go
pump/storage/sorter.go
pump/storage/vlog.go

Issue Number: close https://github.com/pingcap/tidb-binlog/issues/1203
1. update go version to 1.19
2. run `make fmt`
Tests 
- Unit test
- No code
Code changes
Side effects

fmt: format code with go 1.19

---

drainer/syncer.go
drainer/syncer_test.go

Issue Number: close #1228
as title
Tests 
- Unit test
- No code
Code changes
Side effects

skip the "cancled" ddl in ddl history

---

drainer/config.go
drainer/server.go
drainer/util.go

Issue Number: ref https://github.com/pingcap/tidb-binlog/issues/1137
switch create table to batch create table to solve too many versions problem.
Tests 
- Unit test
Code changes
- None
Side effects
- None

drainer: fix too much version when initializing table infos

---

pkg/etcd/etcd.go

Issue Number: close https://github.com/pingcap/tidb-binlog/issues/1236
Add `AutoSyncInterval` configuration in creating etcd client.
Tests 
- None
Code changes
- None
Side effects
- None
- None
```release-note
fix the problem that drainer/pump can't work when pd's topology changes
```

*: add auto sync configuration in creating etcd client

---

Makefile
drainer/binlog_item.go
drainer/config.go
drainer/loopbacksync/loopbacksync.go
drainer/safepoint.go
drainer/schema.go
drainer/schema_test.go
drainer/server.go
drainer/sync/mysql_test.go
drainer/sync/oracle_test.go
drainer/sync/syncer_test.go
drainer/translator/oracle_test.go
drainer/util.go
pkg/loader/load.go
pkg/loader/util.go
pkg/sql/sql.go
pump/storage/sorter.go
pump/storage/vlog.go

cherry-pick #1234 and #1239
---
Issue Number: ref https://github.com/pingcap/tidb-binlog/issues/1137
1. support load table infos from tidb
2. add gc safepoint ttl update to avoid table info is gced
Tests 
- Unit test
- No code
Code changes
Side effects
```release-note
None
```

drainer: support load table infos to save memory and add gc safepoint update (#1233)

---

drainer/syncer.go
drainer/syncer_test.go

Issue Number: close #1317
Tests 
- Unit test
Code changes
Side effects
```release-note
If the whole transaction is filtered, release the memory
```

drainer: if all DML is filtered, return `true` `ignore`
